### PR TITLE
Workbench Bug Fixes

### LINKED ISSUE #28: After genesis, the workbench's next-actor ID is different than builtin-actors test VM.
After genesis, the next actor created in the workbench will have ID 105

In the builtin actors' test VM implementation, the expectation is that new actors begin from ID 103. This causes the test to break on some hardcoded assertions of expected actor ID creation.

### LINKED ISSUE #31: Reward actor state summary check throws error
During state-invariant checking on the workbench VM, a (de)serialization error occurs when attempting to load the reward actor state. This occurs even if the reward actor state is checked immediately after genesis on a freshly instantiated VM. 

Some other actors (datatcap, multisig tested so far) are able to successfully have their state inspected with no issues. 

When attempting to load the RewardState from ActorState.state the following error is hit:
```
thread 'problematic_test' panicked at 'called `Result::unwrap()` on an `Err` value: Failed iterating map: Serialization error for Cbor protocol: RequireLength { name: "tuple", expect: 11, value: 6 }
```

### PR DESCRIPTION
**Pull request by alexytsu**
Closes #31 
Closes #28 

Previously, running the builtin-actor's state invariants check on genesis state of the workbench was revealing errors. 

These fixes ensure that the genesis state of the workbench is compliant with the expected invariants.

### CODE REVIEW

**Comment by alexytsu** [comment]
@anorth a side note: I had originally accidentally pushed these changes to main (then force pushed to restore that branch). 

Just as an fyi, if you consider branch protection rules worthwhile here.

File: builtin/src/lib.rs [hunk 1]
```diff
@@ -21,7 +22,10 @@ pub fn setup() -> ExecutionWrangler {
     )
     .unwrap();
     let spec = GenesisSpec::default(manifest_data_cid);
-    let _genesis = create_genesis_actors(&mut builder, &spec).unwrap();
-    let bench = builder.build().unwrap();
+    let genesis = create_genesis_actors(&mut builder, &spec).unwrap();
+    // check that the genesis state matches assumptions in the builtin-actors test code
+    assert_eq!(genesis.faucet_id, TEST_FAUCET_ADDR.id().unwrap());
+    let circulating_supply = spec.reward_balance + spec.faucet_balance;
```
Comment (anorth) [inline builtin/src/lib.rs:28]: The reward actor balance isn't part of the circulating supply. Does everything work ok if you remove that here?

File: builtin/tests/hookup.rs [hunk 2]
```diff
@@ -31,7 +31,8 @@ fn test_hookup() {
 
     let spec = GenesisSpec::default(manifest_data_cid);
     let genesis = create_genesis_actors(&mut builder, &spec).unwrap();
-    let bench = builder.build().unwrap();
+    let circulating_supply = spec.reward_balance + spec.faucet_balance;
```
Comment (anorth) [inline builtin/tests/hookup.rs:34]: Ditto on reward balance.

Since this is duplicated, could you return the circulating supply in the genesis spec explicitly, encapsulating any calculation like this?

File: builtin/src/lib.rs (hunk 1 above)
Comment (alexytsu) [reply builtin/src/lib.rs:28]: I think perhaps the name `circulating_supply` is inappropriate for the purpose here.

In builtin-actors the implementation for the TestVM also includes reward balance. https://github.com/filecoin-project/builtin-actors/blob/3eb3cec1213f5e5a64ca848069f70ca15db392e7/test_vm/src/lib.rs#L96

It's then used here to inject an expectation into the check_state_invariants. https://github.com/filecoin-project/builtin-actors/blob/3eb3cec1213f5e5a64ca848069f70ca15db392e7/integration_tests/src/util/mod.rs#L61. This check needs to compare an expectation with the sum of all actors' balances.

Comment (anorth) [reply builtin/src/lib.rs:28]: The existing code around circulating supply is generally sloppy and wrong. From tests point of view, it's generally just an input needed for some calculations.

The invariant check you linked to should be using something called total supply instead, which is the sum of all balances (and is something the VM should enforce, not the actors). So maybe you can call this total supply, but it's then not the right thing for the circulating supply syscall to return for calculations, and we need such a value too. But I guess you can leave that wrong for now.

**Review by anorth — APPROVED** [review]
Ok after renaming to total supply, but it's pointing to some unfinished business.

**Comment by alexytsu** [comment]
Given that this is fixed in the tests side https://github.com/filecoin-project/builtin-actors/pull/1466. No further action is needed here. 

A followup to update the builtin-actors dependency will pull the new check_invariants logic.
